#ifndef CTKPOPUPWIDGET_GLOBAL_H
#define CTKPOPUPWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CTK_LIBRARY)
#  define CTK_WIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define CTK_WIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // CTKPOPUPWIDGET_GLOBAL_H
